### ISSUE TITLE
matter controller - gerät per QR-Coder über Kamera anlernen - Invalid pairing code

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#245]
matter 0.3.0

- Matter Device an Google Home angelernt
- Im Matter Controller über Pairing-Code Menü den Code aus derApp manuell eingegeben und somit Matter Gerät im Controller hinzugefügt -> i.O.
- Node entfernt und diesesmal über Pairing Code Menü die Kamera verwendet und den QR Code aus der Google Home App gescannt. Es kommt ein Hinweis, das ein ungültiger Pairing Code verwendet wurde

Log
```
2024-12-20 22:13:43.923 - debug: matter.0 (1019) 2024-12-20 22:13:43.923 DEBUG MdnsScanner Sending 2 query records for 1 queries with 0 known answers. Re-Announce in 48 seconds
2024-12-20 22:14:13.584 - debug: matter.0 (1019) 2024-12-20 22:14:13.584 DEBUG MdnsScanner Removing operational device 74FA7661299E0E12-00000000CDDD043B._matter._tcp.local from cache (interface ens18) because of ttl=0
2024-12-20 22:14:13.584 - debug: matter.0 (1019) 2024-12-20 22:14:13.584 DEBUG MdnsScanner Removing commissionable device 9AE0393AF9D621AB._matterc._udp.local from cache (interface ens18) because of ttl=0
2024-12-20 22:14:13.622 - debug: matter.0 (1019) 2024-12-20 22:14:13.622 DEBUG MdnsScanner Adding operational device 74FA7661299E0E12-00000000CDDD043B._matter._tcp.local in cache (interface ens18, ttl=4500) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: 4933+40962 DN: undefined RI: undefined PI: undefined
2024-12-20 22:14:13.684 - debug: matter.0 (1019) 2024-12-20 22:14:13.684 DEBUG MdnsScanner Found commissionable device C4D69DC6B23B6DC5._matterc._udp.local with data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: 65535 PH: 36 ICD: 0 VP: 4933+40962 DN: undefined RI: 04003C8F1BB650A0B502D484B318AD395F2C PI:
2024-12-20 22:14:31.925 - debug: matter.0 (1019) 2024-12-20 22:14:31.924 DEBUG MdnsScanner Sending 2 query records for 1 queries with 0 known answers. Re-Announce in 96 seconds
2024-12-20 22:15:23.809 - debug: matter.0 (1019) Handle message controllerCommissionDevice {"command":"controllerCommissionDevice","message":{"qrCode":"MT:OIVJ0AJZ1655I12UQ10","manualCode":""},"from":"system.adapter.admin.0","callback":{"message":{"qrCode":"MT:OIVJ0AJZ1655I12UQ10","manualCode":""},"id":84,"ack":false,"time":1734729323808},"_id":18531897}
2024-12-20 22:15:23.809 - debug: matter.0 (1019) 2024-12-20 22:15:23.809 DEBUG PromiseQueue Add promise to queue on place 1
2024-12-20 22:15:23.809 - debug: matter.0 (1019) 2024-12-20 22:15:23.809 DEBUG PromiseQueue Processing promise from queue ... Current queue length: 1 Already running: 0
2024-12-20 22:15:23.811 - warn: matter.0 (1019) Error while executing command "controllerCommissionDevice": Invalid pairing code
at ManualPairingCodeSchema.decodeInternal (/opt/iobroker/node_modules/@matter/types/dist/cjs/schema/PairingCodeSchema.js:173:13)
at ManualPairingCodeSchema.decode (/opt/iobroker/node_modules/@matter/types/dist/cjs/schema/Schema.js:37:25)
at Controller.commissionDevice (/opt/iobroker/node_modules/iobroker.matter/build/matter/ControllerNode.js:296:69)
at Controller.handleCommand (/opt/iobroker/node_modules/iobroker.matter/build/matter/ControllerNode.js:105:39)
at /opt/iobroker/node_modules/iobroker.matter/build/main.js:211:64
at func (/opt/iobroker/node_modules/@matter/general/dist/cjs/util/PromiseQueue.js:49:19)
at #run (/opt/iobroker/node_modules/@matter/general/dist/cjs/util/PromiseQueue.js:71:7)
at PromiseQueue.add (/opt/iobroker/node_modules/@matter/general/dist/cjs/util/PromiseQueue.js:52:14)
at #onMessage (/opt/iobroker/node_modules/iobroker.matter/build/main.js:208:47)
at MatterAdapter.emit (node:events:530:35)
2024-12-20 22:15:23.811 - debug: matter.0 (1019) 2024-12-20 22:15:23.811 DEBUG PromiseQueue Promise processed ... Still running: 0
```

**Comment by Apollon77** [comment]
fixed in next version

**Comment by Feuer-sturm** [comment]
matter 0.3.3
issue is fixed
