### ISSUE TITLE
Re-announce and factory reset of device/bridge does not work yet

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.matter#72]
No matter if bridge or device, while ahving commissoning window open and pressing re-announce we get noticed that it is not implemented yet. 
Furthermore pressing factory reset fails in both cases 

```
Error while handling command "deviceFactoryReset" for device d8627c2d-3f35-44a4-90fa-bc59b172ec10: TypeError: Cannot read properties of undefined (reading '8') at Verhoeff.computeChecksum (/opt/iobroker/node_modules/@project-chip/matter.js/src/math/Verhoeff.ts:43:46) at ManualPairingCodeSchema.encodeInternal (/opt/iobroker/node_modules/@project-chip/matter.js/src/schema/PairingCodeSchema.ts:207:34) at ManualPairingCodeSchema.encode (/opt/iobroker/node_modules/@project-chip/matter.js/src/schema/Schema.ts:12:21) at Function.pairingCodesFor (/opt/iobroker/node_modules/@project-chip/matter.js/src/behavior/system/commissioning/CommissioningBehavior.ts:236:55) at Object.get pairingCodes [as pairingCodes] (/opt/iobroker/node_modules/@project-chip/matter.js/src/behavior/system/commissioning/CommissioningBehavior.ts:297:50) at Commissioning$State.descriptor.get [as pairingCodes] (/opt/iobroker/node_modules/@project-chip/matter.js/src/behavior/state/managed/values/StructManager.ts:249:32) at Device.getState (/opt/iobroker/node_modules/iobroker.matter/src/matter/BaseServerNode.ts:71:94) at Device.handleCommand (/opt/iobroker/node_modules/iobroker.matter/src/matter/BaseServerNode.ts:131:45) at MatterAdapter.onMessage (/opt/iobroker/node_modules/iobroker.matter/src/main.ts:196:40)
```

**Comment by Apollon77** [comment]
should be fixed by upgrading matter.js ....

**Comment by foxriver76** [comment]
I think there is also implementation missing for re-announce 
![grafik](https://github.com/user-attachments/assets/7ebafe25-578f-4950-a973-b26fda5a80ec)

**Comment by Apollon77** [comment]
lol ... it is announcing just not returning ok :-))

**Comment by Apollon77** [comment]
I prepare a PR with update
